import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Header from "@/components/ui/header";
import { ClerkProvider } from "@clerk/nextjs"; 
import { dark } from "@clerk/themes";

const inter = Inter({subsets:["latin"]})

export const metadata = {
  title: "TranzitAi",
  description: "Generated by create TranzitAi",
};

export default function RootLayout({ children }) {
  return (

 <ClerkProvider appearance={{
  baseTheme: dark,  
 }}>

    <html lang="en" suppressHydrationWarning> 
      <body className={`${inter.className}`}
      >

<ThemeProvider
attribute ="class"
defaultTheme="dark"
enableSystem
disableTransitionOnChange
>

{/* header  */}
<Header />
 <main className= "min-h-screen"> {children}</main>

{/* footer */}
<footer className="bg-accent/50 py-12">
  <div className="container mx-auto px-4 text-center text-gray-200" >Made with wajid Ullah & Mamoor Khan</div>
</footer>


</ThemeProvider>
      </body>
    </html>
</ClerkProvider>


  );
}
